### ISSUE TITLE
老哥你的live2d 参数可以看一下嘛，没搞懂怎么移动位置
按照文档里操作不生效，conifg.yml

### ISSUE THREAD

**Issue by dalaoshi777** [fguby/fguby.github.io#1]

**Comment by fguby** [comment]
![image](https://user-images.githubusercontent.com/33178517/75648903-79641380-5c8c-11ea-91da-cd2b47e17368.png)

**Comment by dalaoshi777** [comment]
谢谢大佬，学到了
